### ISSUE TITLE
[Bug] Order of declaration async tasks completely change the execution flow of Workflow

### ISSUE THREAD

**Issue by LikDioxo** [temporalio/sdk-php#207] opened 2022-07-18 11:00 UTC
### What are you really trying to do?

I was trying to create a Workflow that could be stopped by sending the signal and that simultaneously run several tasks.
The idea behind simultaneous tasks consists of waiting for a signal with data and trying to get this data in case that signal wasn't called.
So generally workflow consists of 4 asynchronous tasks:

1. "main" - a task that contains all other code and can be rejected by sending a specific signal
2. Rejection task - checks for signal and reject "main" task when the signal is received
3. Task waiting for the signal with required data
4. Task that calls activity to get the same data as the previous task. Also contains a timer and infinitely calls the activity until get the required data.

### Describe the bug

Depending on the order of declaring the two last tasks (that wait for a signal with data and that call activity to get that data) "main" task can either be rejected when one of the tasks finishes or can proceed successfully.

### Minimal Reproduction

```php
    private bool $isSignaled = false;
    private bool $isRejected = false;

    private Workflow\CancellationScopeInterface $first;
    private Workflow\CancellationScopeInterface $second;

    #[WorkflowMethod]
    public function execute(): \Generator
    {
        $workflowPromise = Workflow::async(
            function () {
                $this->first = Workflow::async(
                    function () {
                        yield Workflow::await(fn() => $this->isSignaled);

                        $this->second->cancel();
                        print "First finished";
                    }
                );

                $this->second = Workflow::async(
                    function () {
                        yield Workflow::timer(5);

                        $this->first->cancel();
                        print "Second finished";
                    }
                );

                yield Promise::race([$this->second, $this->first]);

                print "Main finished";
            }
        )->then(onRejected: fn() => print "Main rejected!");

        Workflow::async(
            function () use ($workflowPromise) {
                yield Workflow::await(fn() => $this->isRejected);
                $workflowPromise->cancel();
            }
        );

        yield $workflowPromise;
    }

    #[Workflow\SignalMethod]
    public function signal(): void
    {
        $this->isSignaled = true;
    }
```

In such flow, the output is following. When the second task finishes after the timer the message "Main rejected!" is displayed.
In case I send a signal before the timer is finished the message "Main finished" is displayed which is the expected result.

But when I declare $this->second before $this->first in both cases "Main finished" is displayed.

Expected behavior: order of declaration async tasks doesn't affect the normal flow of execution.
Actual behavior: in some order of declaration async tasks "main" task is rejected.

### Additional context
![image](https://user-images.githubusercontent.com/45299516/179424601-1e7a188e-01d4-43e7-8035-e9d9757417d1.png)
![image](https://user-images.githubusercontent.com/45299516/179424641-4f7bd6d2-1e40-46b3-9828-ef98d1d7c07f.png)

**Comment by seregazhuk** [comment] 2022-07-23 10:08
@LikDioxo I have found the issue. The problem is with `Workflow::await()`. It doesn't resolve/reject correctly. Thus the main async becomes rejected. In both your cases it should be resolved, not rejected. Even though both internal async-s were canceled/rejected the main async completes and thus `print "Main finished";` should be executed. Please, don't depend on the result of the main async in your code. And the fix will be released the next week (Wednesday).

**Closed** 2022-08-01 18:38 UTC
Labels: Bug
