### ISSUE TITLE
[Bug?] Workflow not completing unless all async coroutines finish or are cancelled manually

### ISSUE THREAD

**Issue by benalf** [temporalio/sdk-php#140] opened 2022-02-01 17:31 UTC
### Describe the bug
Still not sure if it a bug or an intended feature.

If there are any unfinished async closures and workflow somehow reaches a finishing condition like a regular `return` statement or a non-retryable `Exception`, the workflow will be kept in a running state until all async closures are finished even after evaluating the return/exception.

In case it's an intended feature and the user is supposed to manually cleanup all open resources, it becomes difficult to do so cleanly in certain cases.
The most annoying example is running a long activity with an async completion in a coroutine. Since there's no heartbeat (and it wouldn't make sense to heartbeat for days either), there's doesn't seem to be an easy way to cancel it without sending a manual completion through the client itself.

### Minimal Reproduction
Full project with a docker-compose in the attached `repro.zip`. `docker-compose up` to run the env, `docker-compose exec app php app.php execute` to run the workflow.

Even if the workflow evaluates an `Exception` or does a `return`, it still is stuck in a `Running` state until all coroutines are closed. Bug or a feature?

#### Relevant bits:
Workflow
```php
class BlockedWorkflow implements BlockedWorkflowInterface
{
    private $regularActivity;
    private bool $timerFired = false;
    private $someDataFromCoroutineActivity = null;

    public function __construct(
        private LoggerInterface $logger = new Logger(),
    ) {
        $this->regularActivity = Workflow::newActivityStub(
            RegularActivityInterface::class,
            ActivityOptions::new()
                ->withScheduleToCloseTimeout(CarbonInterval::minutes(10))
                ->withHeartbeatTimeout(3)
                ->withCancellationType(ActivityCancellationType::WAIT_CANCELLATION_COMPLETED)
        );
    }

    public function run()
    {
        $timerScope = Workflow::async(
            fn () => yield Workflow::timer(3)->then(fn() => $this->timerFired = true) // if timer value exceeds time to wf return, that return is also blocked
        );

        $activityScope = Workflow::async(
            fn () => $this->someDataFromCoroutineActivity = yield $this->regularActivity->runActivity()
        );

        yield Workflow::await(fn () => $this->timerFired || $this->someDataFromCoroutineActivity);

        if ($this->timerFired) {
            $this->logger->info('Workflow Terminating with Exception');
            // $scope->cancel(); // unless cancelled, the wf doesn't terminate until activity finishes
            throw new \Exception();
        }

        $this->logger->info('Workflow Terminating with normal return');
        // $timerScope->cancel(); // unless cancelled, the wf doesn't terminate until timer finishes

        return $this->someDataFromCoroutineActivity;
    }
}
```

Activity
```php
<?php

#[ActivityInterface]
class RegularActivity implements RegularActivityInterface
{
    public function __construct(
        private LoggerInterface $logger = new Logger(),
    ) {
    }

    #[ActivityMethod]
    public function runActivity(): string
    {
        $this->logger->info('Starting regular activity with a 1s sleep loop');

        for ($i = 0; $i < 5; $i++) {
            $this->logger->info('Activity tick');
            sleep(1);
            Activity::heartbeat($i);
        }

        $this->logger->info('Activity terminating');

        return 'Activity result';
    }
}
```

### Environment/Versions

- OS and processor: Linux
- Temporal Version: `temporalio/auto-setup:1.14.4` with 1.1.0 sdk-php on `php:8.1-cli-alpine`
- Running in Docker

[repro.zip](https://github.com/temporalio/sdk-php/files/7980666/repro.zip)

**Comment by wolfy-j** [comment] 2022-02-14 10:59
Just to confirm, all the activities are canceled correctly when you send the cancel command to the workflow? Workflows are not expected to die on exception unless you clearly marked it as application exception. Temporal will attempt to restart and replay it until it's fixed.

**Comment by benalf** [comment] 2022-02-14 14:35
Sorry, detouring a bit from your question (we haven't tried cancelling the workflow itself, we tried cancelling all running scopes/activities to let it gracefully terminate itself).

I think the "issue" can actually be reduced to async closure scopes blocking workflow completion. The activity termination I was initially focused on was more of a red herring.

```php
    #[WorkflowMethod("run")]
    public function run() {
        $scope = Workflow::async(fn () => yield Workflow::timer(15)->then(fn () => $this->timedOut = true));

        return 'ok'; // will wait for scope to close or needs to be manually cancelled before the workflow will be marked as Completed
    }
```
It totally makes sense. ~~However, it becomes difficult to cancel a scope if it spawns an activity with async completion since there's no heartbeat.~~

While playing with a minimal repro code, I tried cancelling a scope with async completion activity in it without adding any hearbeat/cancellationtype ...and it just cancels it (solving the issue of me going through the client).

```php
    #[WorkflowMethod("run")]
    public function run() {
        $activity = Workflow::newActivityStub(
            SomeAsyncCompletionActivity::class,
            ActivityOptions::new()
                ->withScheduleToCloseTimeout(1000)
                // ->withCancellationType(ActivityCancellationType::WAIT_CANCELLATION_COMPLETED) // can't be used
                ->withRetryOptions(
                    RetryOptions::new()->withMaximumAttempts(1)
                )
        );

        $scope = Workflow::async(fn () => yield $activity->process());
        yield Workflow::timer(1); // breathing room


        $scope->cancel(); // works fine without a heartbeat

        return 'ok';
    }
```
That works fine and I see a pretty `ActivityTaskCancelRequested` in the activity history. Somehow from the docs I tunneled on
> Cancellation is only delivered to Activities that record heartbeats

and thought it's not really an option with async completion. Am I misunderstanding something fundamental with cancellations and can you confirm async coroutines should be blocking workflow returns?

**Closed** 2022-02-19 16:17 UTC
Labels: Bug

**Comment by wolfy-j** [comment] 2022-02-19 16:19
Async coroutines will block the return from the workflow until they are complete or canceled. It's intended behavior.
