### ISSUE TITLE
[Bug] worker returns "Workflow with the specified run identifier.."

### ISSUE THREAD

**Issue by antmendoza** [temporalio/sdk-php#361] opened 2023-10-09 08:58 UTC
### What are you really trying to do?

The customer run a query to a workflow execution (from an activity, using the workflow client) , and they got the following error 

`workflow_process_handle_query: Workflow with the specified run identifier \"abc-abc... \" not found`
https://github.com/temporalio/sdk-php/blob/e5b375f10f45ddf5a0b1e2fd1a633a65b9594474/src/Internal/Transport/Router/WorkflowProcessAwareRoute.php#L23

The query works for most of the workflow executions, but for other (small %)  it fails, does not matter how many times you run the query

The issue got resolved after restarting the workers. 

### Environment/Versions

SDK version: 2.5.4

### Additional context

Clicking in the query tab, in the UI, returns the following error for the affected workflow executions

**Comment by roxblnfk** [comment] 2023-10-09 09:55
I thin it was fixed in 2.6.0 with RoadRunner 2023.3
See https://github.com/temporalio/sdk-php/pull/340

**Comment by rustatian** [comment] 2023-10-09 10:01
@antmendoza @roxblnfk Yeah, looks like we already fixed this issue. Should be `2023.3` RR + `2.6.1` PHP-SDK

**Comment by roxblnfk** [comment] 2023-10-19 20:52
Just reopen the issue if the problem is reproducible on SDK version 2.6.

**Closed by roxblnfk** 2023-10-19 20:52 UTC
Labels: Bug
