### ISSUE TITLE
[Bug] Seeing a spike in CPU utilization in presence of the following error

### ISSUE THREAD

**Issue by antmendoza** [temporalio/sdk-php#304] opened 2023-05-16 12:25 UTC
### Describe the bug
In presence of the attached error, the user shows a spike in CPU utilization

opening an issue as @wolfy-j requested 

[worker-logs.txt](https://github.com/temporalio/sdk-php/files/11487743/worker-logs.txt)

Adding metrics on CPU and memory utilization for the worker 
<img width="417" alt="Screenshot 2023-05-22 at 17 06 44" src="https://github.com/temporalio/sdk-php/assets/514932/e8f052ae-7cbd-44e7-84a7-fad937fd7e43">
<img width="224" alt="Screenshot 2023-05-22 at 17 05 20" src="https://github.com/temporalio/sdk-php/assets/514932/f56f4628-4c8c-4e52-a181-9be72fb0ed9f">

### Environment/Versions

- OS and processor: [e.g. M1 Mac, x86 Windows, Linux]
- Temporal Version: [e.g. 1.14.0?] and/or SDK version
- Are you using Docker or Kubernetes or building Temporal from source?

**Comment by rustatian** [comment] 2023-05-16 17:07
Hey @antmendoza 👋🏻 
As far as I can see from the logs, you're using the rather outdated version of the rr-temporal plugin. Could you please show me your RR version?

**Comment by manishrocksag** [comment] 2023-05-23 13:24
Hello
Previously we were using roadrunner version 2.12.1 and we upgraded to roadrunner version 2023.1.1 on Tue May 9 12:53:35 2023 (CEST).  We saw this spike on 2023-05-09T11:17:32 or 2023-05-09T13:17:32 (CEST) We are using temporal/sdk version of 2.5.0. Is this due to upgrade?

After the upgrade, we have not received this error again.

**Comment by antmendoza** [comment] 2023-07-07 10:52
> After the upgrade, we have not received this error again.

@manishrocksag do you think we can close this issue?

**Comment by rustatian** [comment] 2023-09-01 11:16
@manishrocksag Closing the issue, feel free to reopen it if the issue is still exists.

**Closed by rustatian** 2023-09-01 11:16 UTC
